export enum BookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PICKED_UP = 'PICKED_UP',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  NO_SHOW = 'NO_SHOW',
}

export enum BookingDispatchStatus {
  AUTO_ASSIGNED = 'AUTO_ASSIGNED',
  WARNING = 'WARNING',
  MANUAL_REQUIRED = 'MANUAL_REQUIRED',
  MANUALLY_ASSIGNED = 'MANUALLY_ASSIGNED',
}
